graph TD

%% Available styles
classDef Lit_int_ fill:#ffffff, stroke:#0000ff, color:#000000;
classDef Lit_std__string_ fill:#ffffff, stroke:#ff0000, color:#000000;
classDef BinOp fill:#d3ff5b, stroke:#d3ff5b, color:#000000;
classDef Assign fill:#d3ff5b, stroke:#d3ff5b, color:#000000;
classDef Block fill:#d3ff5b, stroke:#d3ff5b, color:#000000;
classDef IfElse fill:#d3ff5b, stroke:#d3ff5b, color:#000000;

%% AST tree
1[block]:::Block
2[block]:::Block
4(a):::Lit_std__string_
5(10):::Lit_int_
3[assignment]:::Assign
3 --> 4
3 --> 5
2 --> 3
6[block]:::Block
9(a):::Lit_std__string_
10(10):::Lit_int_
8[L]:::BinOp
8 --> 9
8 --> 10
11[block]:::Block
13(x):::Lit_std__string_
15(9):::Lit_int_
16(11):::Lit_int_
14[Add]:::BinOp
14 --> 15
14 --> 16
12[assignment]:::Assign
12 --> 13
12 --> 14
11 --> 12
18(a):::Lit_std__string_
21(x):::Lit_std__string_
22(1):::Lit_int_
20[Mul]:::BinOp
20 --> 21
20 --> 22
23(300):::Lit_int_
19[Add]:::BinOp
19 --> 20
19 --> 23
17[assignment]:::Assign
17 --> 18
17 --> 19
11 --> 17
25(x):::Lit_std__string_
27(a):::Lit_std__string_
28(23):::Lit_int_
26[NE]:::BinOp
26 --> 27
26 --> 28
24[assignment]:::Assign
24 --> 25
24 --> 26
11 --> 24
7[if_else]:::IfElse
7 --> 8
7 --> 11
6 --> 7
2 --> 6
1 --> 2
